version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/resume_analyzer
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=resume_analyzer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
